"""Remove role column from User model

Revision ID: b4fdb04396f1
Revises: d8839a6b0cb0
Create Date: 2024-08-02 20:06:42.706024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4fdb04396f1'
down_revision = 'd8839a6b0cb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reset_token')
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('reset_token', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
