"""adding transaction-id for mpesa

Revision ID: ce7ff96db348
Revises: d99f80f254b2
Create Date: 2024-08-13 14:24:59.407266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce7ff96db348'
down_revision = 'd99f80f254b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mpesa_receipt_number', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('mpesa_receipt_number')

    # ### end Alembic commands ###
